# Generated by Django 3.2.25 on 2024-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
