# Generated by Django 3.2.25 on 2024-07-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0004_auto_20240715_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='password',
            new_name='otp',
        ),
        migrations.RenameField(
            model_name='otpcode',
            old_name='username',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='utype',
        ),
    ]
